&shared:
  build: &build_base
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w"
    hooks:
      post:
        - ./scripts/upx_wrapper.sh "{{ .Path }}" "{{ .Runtime.Goos }}" "{{ .Runtime.Goarch }}"

builds:
  - <<: *build_base
    id: uaws-cloudfront-create-invalidation
    main: ./cmd/uaws-cloudfront-create-invalidation/
    binary: uaws-cloudfront-create-invalidation
  - <<: *build_base
    id: uaws-ecr-get-login-password
    main: ./cmd/uaws-ecr-get-login-password/
    binary: uaws-ecr-get-login-password
  - <<: *build_base
    id: uaws-s3-sync
    main: ./cmd/uaws-s3-sync/
    binary: uaws-s3-sync
archives:
  - builds:
      - uaws-cloudfront-create-invalidation
      - uaws-ecr-get-login-password
      - uaws-s3-sync
    format: binary
checksum:
  name_template: 'checksums.txt'
