builds:
  - id: uaws-cloudfront-create-invalidation
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/uaws-cloudfront-create-invalidation/
    binary: uaws-cloudfront-create-invalidation
    ldflags:
      - "-s -w"
    hooks:
      post:
        - ./scripts/upx_wrapper.sh "{{ .Path }}"
  - id: uaws-ecr-get-login-password
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/uaws-ecr-get-login-password/
    binary: uaws-ecr-get-login-password
    ldflags:
      - "-s -w"
    hooks:
      post:
        - ./scripts/upx_wrapper.sh "{{ .Path }}"
  - id: uaws-s3-sync
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/uaws-s3-sync/
    binary: uaws-s3-sync
    ldflags:
      - "-s -w"
    hooks:
      post:
        - ./scripts/upx_wrapper.sh "{{ .Path }}" "{{ .Runtime.Goos }}" "{{ .Runtime.Goarch }}"
archives:
  - builds:
      - uaws-cloudfront-create-invalidation
      - uaws-ecr-get-login-password
      - uaws-s3-sync
    format: binary
checksum:
  name_template: 'checksums.txt'
