name: ci
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Run go vet
        run: go vet ./...
      - name: Run go build
        run: go build ./...
      - name: Run go test
        run: go test ./... -v -race
