name: release-test
on:
  pull_request:
    paths:
      - '.github/workflows/release-test.yaml'
      - '.goreleaser.yml'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v4
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          install-only: true
      - name: Run GoReleaser
        run: goreleaser release --clean --skip-publish --snapshot
