name: release
on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          install-only: true
      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update file list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          tag=${GITHUB_REF#refs/tags/}

          git fetch origin gh-pages
          git checkout gh-pages
          git merge --no-ff ${GITHUB_REF}

          mkdir -p releases
          ./uaws get_download_urls ${tag} > releases/${tag}
          if [[ "${tag}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
          then
            ./uaws get_download_urls latest > releases/latest
          fi

          git add releases
          git commit -m "Update releases ${tag} information"
          git push origin gh-pages
