name: script test / osx
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  uaws-install:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install utils
        run: brew install coreutils
      - name: Install ecr-get-login-password subcommand
        run: ./uaws install ecr-get-login-password
      - name: Check installed command
        run: |
          export PATH=${PATH}:${HOME}/.local/bin
          which uaws-ecr-get-login-password
          test -L $(which uaws-ecr-get-login-password)
          test -x $(grealpath $(which uaws-ecr-get-login-password))
      - name: Check upgrade
        run: ./uaws upgrade
  uaws-install-with-token:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install utils
        run: brew install coreutils
      - name: Show download URLs
        run: ./uaws get_download_urls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install ecr-get-login-password subcommand
        run: ./uaws install ecr-get-login-password
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check installed command
        run: |
          export PATH=${PATH}:${HOME}/.local/bin
          which uaws-ecr-get-login-password
          test -L $(which uaws-ecr-get-login-password)
          test -x $(grealpath $(which uaws-ecr-get-login-password))
      - name: Check upgrade
        run: ./uaws upgrade
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
